// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtP2FdCIJNczl4TvdwizwEJH_bwATWtbw',
    appId: '1:353061834463:web:c214fe3e42ef5db7dc636a',
    messagingSenderId: '353061834463',
    projectId: 'garagelink-7a168',
    authDomain: 'garagelink-7a168.firebaseapp.com',
    storageBucket: 'garagelink-7a168.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC435eeuctT1b3S5GXbO2fNtw56F7GZYiY',
    appId: '1:353061834463:android:8052b27b0c138fe2dc636a',
    messagingSenderId: '353061834463',
    projectId: 'garagelink-7a168',
    storageBucket: 'garagelink-7a168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXqN6r6kpWLlZTp0VE2fbYMhFBI35d0GY',
    appId: '1:353061834463:ios:a53baeacaa19339cdc636a',
    messagingSenderId: '353061834463',
    projectId: 'garagelink-7a168',
    storageBucket: 'garagelink-7a168.firebasestorage.app',
    iosBundleId: 'com.example.garagelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXqN6r6kpWLlZTp0VE2fbYMhFBI35d0GY',
    appId: '1:353061834463:ios:a53baeacaa19339cdc636a',
    messagingSenderId: '353061834463',
    projectId: 'garagelink-7a168',
    storageBucket: 'garagelink-7a168.firebasestorage.app',
    iosBundleId: 'com.example.garagelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtP2FdCIJNczl4TvdwizwEJH_bwATWtbw',
    appId: '1:353061834463:web:854c0a11794144b1dc636a',
    messagingSenderId: '353061834463',
    projectId: 'garagelink-7a168',
    authDomain: 'garagelink-7a168.firebaseapp.com',
    storageBucket: 'garagelink-7a168.firebasestorage.app',
  );

}